services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: wic-app
      POSTGRES_PASSWORD: wic-app
      POSTGRES_DB: wic-app
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wic-app -d wic-app"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
