"""add releases table

Revision ID: 2542ed7a7909
Revises: 5161efa678fd
Create Date: 2026-03-15 00:41:48.619452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2542ed7a7909'
down_revision: Union[str, Sequence[str], None] = '5161efa678fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('releases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('firestore_doc_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='releasestatus'), nullable=False),
    sa.Column('format', sa.Enum('TEN_INCH', 'TWELVE_INCH', 'DOUBLE_TWELVE', name='releaseformat'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_releases_artist_id'), 'releases', ['artist_id'], unique=False)
    op.create_index(op.f('ix_releases_firestore_doc_id'), 'releases', ['firestore_doc_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_releases_firestore_doc_id'), table_name='releases')
    op.drop_index(op.f('ix_releases_artist_id'), table_name='releases')
    op.drop_table('releases')
    # ### end Alembic commands ###
