"""add campaigns and campaign_events tables

Revision ID: 9f258f117a81
Revises: 2542ed7a7909
Create Date: 2026-03-15 00:48:19.871695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f258f117a81'
down_revision: Union[str, Sequence[str], None] = '2542ed7a7909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('release_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'FUNDED', 'FAILED', 'REFUNDING', 'CLOSED', name='campaignstatus'), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('current_count', sa.Integer(), nullable=False),
    sa.Column('presale_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('retail_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_release_id'), 'campaigns', ['release_id'], unique=True)
    op.create_table('campaign_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=64), nullable=False),
    sa.Column('to_status', sa.String(length=64), nullable=False),
    sa.Column('triggered_by', sa.String(length=128), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_events_campaign_id'), 'campaign_events', ['campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_events_campaign_id'), table_name='campaign_events')
    op.drop_table('campaign_events')
    op.drop_index(op.f('ix_campaigns_release_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
